ansible_user: ansible
ansible_password: "{{ vault_windows_password }}"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_port: 5985
ansible_winrm_scheme: http
ansible_become: false
